spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp_mgmt
    username: root
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/schema

  graphql:
    graphiql:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8081

logging:
  level:
    org.springframework.web: debug