spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp_mgmt
    username: root
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        generate_statistics: true

  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:/schema

  graphql:
    graphiql:
      enabled: true
#      path: /graphql

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8081

logging:
  level:
    org.springframework.web: debug
#    com.legalmatch.emp_mgmt: debug
#    org.hibernate.type: trace